name: VillagerUtil
author: Apeiros
description: A small Slimefun4 addon that adds a few convenience features related to villagers
main: me.apeiros.villagerutil.VillagerUtil
website: https://github.com/Apeiros-46B/VillagerUtil
version: ${project.version}
api-version: 1.18
depend:
- Slimefun
commands:
  resetvillager:
    description: 重置村民的经验与交易
    usage: 制作一个村民交易棒并右键点击交易锁定的村名
