name: Sync To Gitee

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: git-mirror

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GUIZHAN_GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:SlimefunGuguProject/VillagerUtil.git"
          destination-repo: "git@gitee.com:ybw0014/VillagerUtil-CN.git"
